version: '3.9'

services:
  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service_user -d auth_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-app-net

  authservice:
    build: .
    container_name: authservice
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
      - DB_USERNAME=user_service_user
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      postgres-auth:
        condition: service_healthy
    networks:
      - my-app-net

volumes:
  postgres-auth-data:

networks:
  my-app-net:
    external: true
